CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

ALTER TABLE usuario
    ADD STRIPE_KEY VARCHAR(255) NULL;

UPDATE usuario
SET STRIPE_KEY = uuid_generate_v4()
WHERE STRIPE_KEY IS NULL;

ALTER TABLE usuario
    ALTER COLUMN STRIPE_KEY SET NOT NULL;

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_stripe_key UNIQUE (STRIPE_KEY);